include:
- project: iiidevops-templates/ci-template
  ref: v2.12.6
  file: ci/template.gitlab-ci.yml
stages:
- initial
- scan
- build
- deploy
- test
- userjobs
Copy Code From EE:
  stage: initial
  variables:
    iiidevops: copy-code
  image:
    name: node:16
  before_script:
  - git config --global user.email "gitlab-ci@dev7.iiidevops.org"
  - git config --global user.name "GitLab CI"
  script:
  - git clone -b v3 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev7.iiidevops.org/iiidevops/devopsui-mono.git Mono
  - 'cp Mono/dockerfiles/LITE.Dockerfile ./Dockerfile

    cp Mono/app/lerna.json ./app/lerna.json

    cp Mono/app/apps/lite/package.json ./app/package.json

    cp Mono/build/entrypoint.sh ./build/entrypoint.sh

    cp Mono/build/default.nginx ./build/default.nginx

    cp -r Mono/app/apps/lite ./app/apps

    cp -r Mono/app/apps/shared ./app/apps

    cp -r Mono/iiidevops ./

    '
  - pwd
  - ls -la
  - cd app && yarn
  - pwd
  - ls -la
  - cd -
  - rm -rf Mono
  - "if [ -f common.yaml ]; then\n  rm common.yaml\nfi\n"
  - git add -A
  - git commit -m "Sync from full by bot"
  - git push "https://gitlab-ci-token:$PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    HEAD:$CI_DEFAULT_BRANCH
  - git push "https://gitlab-ci-token:$PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    --tags
  - echo "同步成功，故意拋出錯誤以暫停後續任務執行"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'trigger'
Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: normal
Test--Semgrep SAST code scan:
  variables:
    iiidevops: semgrep
    SEARCH_MAX_DEPTH: 20
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, iiidevops, **/*.md
Test--Anchore SBOM source code scan:
  variables:
    iiidevops: anchore-code
Test--Checkmarx source code scan:
  variables:
    iiidevops: checkmarx
Build image:
  variables:
    iiidevops: build
Build--Scan docker image:
  variables:
    iiidevops: build
Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deploy
Deploy--Web:
  variables:
    iiidevops: deploy
    CHART_WEB_PORT: 80
    CHART_PROXY_BODY_SIZE: 1m
Test--Anchore SBOM:
  variables:
    iiidevops: anchore
Test--ZAP:
  variables:
    iiidevops: zap
    CHART_WEB_PORT: 80
Test--WebInspect:
  variables:
    iiidevops: webinspect
Test--Postman:
  variables:
    iiidevops: postman
    CHART_WEB_PORT: 80
Test--Sideex:
  variables:
    iiidevops: sideex
    CHART_WEB_PORT: 80
